# Generated by Django 5.2.1 on 2025-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
