# Generated by Django 5.2.1 on 2026-03-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_trailer_key_movie_trailer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
