# Generated by Django 5.2.1 on 2026-03-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_backdrop_url_alter_movie_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
